### ISSUE TITLE
Questions from the Readme

### ISSUE THREAD

**Issue by bdpedigo** [flyconnectome/ALPN_crossmatching#1]
Hi @schlegelp, a few questions as promised:

> Neurons can only match within the same developmental (hemi-)lineage.

Is this a hard constraint you want us to impose on the optimization (i.e. we never violate it), some added prior information that we could use to help the optimization, or something where we should see if it "falls out" of whatever we run? I could imagine us trying any of the above so i just want to make sure I know what you mean by "can only match..."

> Some ALPNs are truncated in the hemibrain. We tried to compensate for this during the NBLAST but we currently don't factor in how much we loose due to truncation.

I doubt this will be super important for whatever we run as a first pass, but are these neurons annotated somewhere?

 > For some neurons the lineage annotation might not be accurate. This is because the primary neurite bundles for some lineages (like l2PNs) do not tightly co-fasciculate, and some neurons can look ambiguous.

Related to my question above about whether we want this to be a hard constraint - just wondering if this would be problematic if we did try to enforce that these neurons match and the lineage annotations are slightly off. Also, for the cases where lineage might not be accurate, is it usually at least narrowed down to 2 or 3 lineages?

**Comment by schlegelp** [comment]
> Is this a hard constraint you want us to impose on the optimization (i.e. we never violate it), some added prior information that we could use to help the optimization, or something where we should see if it "falls out" of whatever we run? I could imagine us trying any of the above so i just want to make sure I know what you mean by "can only match..."

In theory this is a hard constraint. However there is a chance that a small number (I'd be surprised if it was more than 5 neurons in total) have been assigned the wrong hemilineage. I was wondering if it could be a semi-hard constraint in the sense that: "we match within hemilineages and only go looking across lineages if we absolutely can't find a decent match". That being said: I suspect that even without applying this constraint you will find that most neurons automatically match within their hemilineage. It might be a good idea to try various approaches from unconstrained to fully constraint?

> I doubt this will be super important for whatever we run as a first pass, but are these neurons annotated somewhere?

True. It's just something to keep in mind: the NBLAST scores can only be as "correct" as the underlying data. I don't think we have that annotated but it's a good idea. I'll see if I can add that as another label for the meta data. 

> Related to my question above about whether we want this to be a hard constraint - just wondering if this would be problematic if we did try to enforce that these neurons match and the lineage annotations are slightly off. Also, for the cases where lineage might not be accurate, is it usually at least narrowed down to 2 or 3 lineages?

Also a good thought. There are some (combinations of) lineages where the assignment is more difficult. If you want to consider this when you formulate the problem: off the top of my head, I'd say be slightly weary of `lPN` vs `l2PN` vs `lv2PN`. All other lineage should be as safe as it gets. Maybe @mmc46 could add to this assessment?

**Comment by mmc46** [comment]
I'd flag those same 3. The lvPNs will have somas in between those, but a very characteristic soma tract, so easy to identify.

**Comment by bdpedigo** [comment]
closing just cause i think this answered all my qs, thanks both!
